'use client';

/**
 * SOW Metadata Editor Component
 *
 * Provides editing interface for SOW-level metadata including:
 * - Coherence (policy notes, sequencing notes)
 * - Accessibility notes
 * - Engagement notes
 * - Course scheduling (weeks, periods per week)
 */

import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { SOWMetadata } from '@/lib/appwrite/types/sow-schema';

interface SOWMetadataEditorProps {
  metadata: SOWMetadata;
  onChange: (metadata: SOWMetadata) => void;
}

export function SOWMetadataEditor({ metadata, onChange }: SOWMetadataEditorProps) {
  const updateField = <K extends keyof SOWMetadata>(field: K, value: SOWMetadata[K]) => {
    onChange({ ...metadata, [field]: value });
  };

  const updateCoherence = (field: 'policy_notes' | 'sequencing_notes', value: string[]) => {
    onChange({
      ...metadata,
      coherence: { ...metadata.coherence, [field]: value },
    });
  };

  // Helper for adding items to arrays
  const addToArray = (
    field: 'policy_notes' | 'sequencing_notes' | 'accessibility_notes' | 'engagement_notes',
    placeholder: string
  ) => {
    const newItem = prompt(`Enter new ${placeholder}:`);
    if (newItem && newItem.trim()) {
      if (field === 'policy_notes' || field === 'sequencing_notes') {
        updateCoherence(field, [...metadata.coherence[field], newItem.trim()]);
      } else {
        updateField(field, [...metadata[field], newItem.trim()]);
      }
    }
  };

  const removeFromCoherence = (field: 'policy_notes' | 'sequencing_notes', index: number) => {
    updateCoherence(
      field,
      metadata.coherence[field].filter((_, i) => i !== index)
    );
  };

  const removeFromArray = (field: 'accessibility_notes' | 'engagement_notes', index: number) => {
    updateField(
      field,
      metadata[field].filter((_, i) => i !== index)
    );
  };

  const updateArrayItem = (
    field: 'policy_notes' | 'sequencing_notes' | 'accessibility_notes' | 'engagement_notes',
    index: number,
    value: string
  ) => {
    if (field === 'policy_notes' || field === 'sequencing_notes') {
      const updated = [...metadata.coherence[field]];
      updated[index] = value;
      updateCoherence(field, updated);
    } else {
      const updated = [...metadata[field]];
      updated[index] = value;
      updateField(field, updated);
    }
  };

  return (
    <div className="space-y-6">
      {/* Display-only computed fields */}
      {(metadata.course_name || metadata.level) && (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <h3 className="font-semibold text-blue-900 mb-2">Course Information (Read-only)</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            {metadata.course_name && (
              <div>
                <span className="text-blue-600">Course Name:</span>
                <p className="font-medium">{metadata.course_name}</p>
              </div>
            )}
            {metadata.level && (
              <div>
                <span className="text-blue-600">Level:</span>
                <p className="font-medium">{metadata.level}</p>
              </div>
            )}
            {metadata.total_lessons && (
              <div>
                <span className="text-blue-600">Total Lessons:</span>
                <p className="font-medium">{metadata.total_lessons}</p>
              </div>
            )}
            {metadata.total_estimated_minutes && (
              <div>
                <span className="text-blue-600">Total Minutes:</span>
                <p className="font-medium">{metadata.total_estimated_minutes}</p>
              </div>
            )}
          </div>
          {metadata.author_agent_version && (
            <p className="text-xs text-blue-500 mt-2">
              Generated by: {metadata.author_agent_version}
              {metadata.generated_at && ` on ${new Date(metadata.generated_at).toLocaleDateString()}`}
            </p>
          )}
        </div>
      )}

      {/* Scheduling */}
      <div className="p-4 border rounded-lg">
        <h3 className="font-semibold mb-3">Course Scheduling</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <Label htmlFor="weeks">Weeks</Label>
            <Input
              id="weeks"
              type="number"
              min={1}
              max={52}
              value={metadata.weeks || ''}
              onChange={(e) => updateField('weeks', e.target.value ? parseInt(e.target.value) : undefined)}
              placeholder="e.g., 36"
            />
            <p className="text-xs text-gray-500 mt-1">Number of weeks in the course</p>
          </div>
          <div>
            <Label htmlFor="periods">Periods Per Week</Label>
            <Input
              id="periods"
              type="number"
              min={1}
              max={10}
              value={metadata.periods_per_week || ''}
              onChange={(e) => updateField('periods_per_week', e.target.value ? parseInt(e.target.value) : undefined)}
              placeholder="e.g., 5"
            />
            <p className="text-xs text-gray-500 mt-1">Number of lesson periods per week</p>
          </div>
        </div>
      </div>

      {/* Coherence - Policy Notes */}
      <div className="p-4 border rounded-lg">
        <div className="flex justify-between items-center mb-3">
          <div>
            <h3 className="font-semibold">Policy Notes</h3>
            <p className="text-sm text-gray-500">Course-level policy guidelines and constraints</p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => addToArray('policy_notes', 'policy note')}
          >
            <Plus className="h-4 w-4 mr-2" /> Add Note
          </Button>
        </div>
        <div className="space-y-2">
          {metadata.coherence.policy_notes.map((note, idx) => (
            <div key={idx} className="flex gap-2">
              <Textarea
                value={note}
                onChange={(e) => updateArrayItem('policy_notes', idx, e.target.value)}
                rows={2}
                className="flex-1"
              />
              <Button
                variant="ghost"
                size="sm"
                onClick={() => removeFromCoherence('policy_notes', idx)}
                className="text-red-500 self-start"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
          {metadata.coherence.policy_notes.length === 0 && (
            <p className="text-sm text-gray-400 italic">No policy notes added</p>
          )}
        </div>
      </div>

      {/* Coherence - Sequencing Notes */}
      <div className="p-4 border rounded-lg">
        <div className="flex justify-between items-center mb-3">
          <div>
            <h3 className="font-semibold">Sequencing Notes</h3>
            <p className="text-sm text-gray-500">Notes about lesson ordering and dependencies</p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => addToArray('sequencing_notes', 'sequencing note')}
          >
            <Plus className="h-4 w-4 mr-2" /> Add Note
          </Button>
        </div>
        <div className="space-y-2">
          {metadata.coherence.sequencing_notes.map((note, idx) => (
            <div key={idx} className="flex gap-2">
              <Textarea
                value={note}
                onChange={(e) => updateArrayItem('sequencing_notes', idx, e.target.value)}
                rows={2}
                className="flex-1"
              />
              <Button
                variant="ghost"
                size="sm"
                onClick={() => removeFromCoherence('sequencing_notes', idx)}
                className="text-red-500 self-start"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
          {metadata.coherence.sequencing_notes.length === 0 && (
            <p className="text-sm text-gray-400 italic">No sequencing notes added</p>
          )}
        </div>
      </div>

      {/* Accessibility Notes */}
      <div className="p-4 border rounded-lg">
        <div className="flex justify-between items-center mb-3">
          <div>
            <h3 className="font-semibold">Accessibility Notes</h3>
            <p className="text-sm text-gray-500">Course-wide accessibility considerations</p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => addToArray('accessibility_notes', 'accessibility note')}
          >
            <Plus className="h-4 w-4 mr-2" /> Add Note
          </Button>
        </div>
        <div className="space-y-2">
          {metadata.accessibility_notes.map((note, idx) => (
            <div key={idx} className="flex gap-2">
              <Textarea
                value={note}
                onChange={(e) => updateArrayItem('accessibility_notes', idx, e.target.value)}
                rows={2}
                className="flex-1"
              />
              <Button
                variant="ghost"
                size="sm"
                onClick={() => removeFromArray('accessibility_notes', idx)}
                className="text-red-500 self-start"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
          {metadata.accessibility_notes.length === 0 && (
            <p className="text-sm text-gray-400 italic">No accessibility notes added</p>
          )}
        </div>
      </div>

      {/* Engagement Notes */}
      <div className="p-4 border rounded-lg">
        <div className="flex justify-between items-center mb-3">
          <div>
            <h3 className="font-semibold">Engagement Notes</h3>
            <p className="text-sm text-gray-500">Strategies for maintaining student engagement</p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => addToArray('engagement_notes', 'engagement note')}
          >
            <Plus className="h-4 w-4 mr-2" /> Add Note
          </Button>
        </div>
        <div className="space-y-2">
          {metadata.engagement_notes.map((note, idx) => (
            <div key={idx} className="flex gap-2">
              <Textarea
                value={note}
                onChange={(e) => updateArrayItem('engagement_notes', idx, e.target.value)}
                rows={2}
                className="flex-1"
              />
              <Button
                variant="ghost"
                size="sm"
                onClick={() => removeFromArray('engagement_notes', idx)}
                className="text-red-500 self-start"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
          {metadata.engagement_notes.length === 0 && (
            <p className="text-sm text-gray-400 italic">No engagement notes added</p>
          )}
        </div>
      </div>
    </div>
  );
}
